"""Apply intuitive column name mappings to normalized clinical Excel files.

This script uses the mapping provided in
`20260312_솔루엠_임상테이블 정리.xlsx` to rename columns in the
normalized Excel outputs (generated by normalize_excel_files.py).

The mapping file includes a "표준 컬럼명 (Target)" that should be used as the
new column name for specific source columns (often in Korean).

Usage:
    python apply_column_mappings.py \
      --normalized <normalized_folder> \
      --mapping <mapping_excel> \
      --out <output_folder>

Example:
    python apply_column_mappings.py \
      --normalized "./clinical_data/normalized_xlsx" \
      --mapping "./clinical_data/20260312_솔루엠_임상테이블 정리.xlsx" \
      --out "./clinical_data/mapped_xlsx"

Notes:
- Only columns that match the mapping (after normalization) are renamed.
- If a column can be mapped in multiple ways, the first applicable mapping is used.
"""

import argparse
import os
import re
from pathlib import Path

import pandas as pd


def normalize_col(col: str) -> str:
    """Normalize a column name in the same way normalization script does."""
    if pd.isna(col):
        return ""
    out = str(col).strip()
    out = re.sub(r"[\r\n\t]+", " ", out)
    out = re.sub(r"\s+", " ", out)
    out = re.sub(r"[^\w]+", "_", out, flags=re.UNICODE)
    out = out.strip("_")
    if not out:
        return ""
    if re.match(r"^[0-9]", out):
        out = "c_" + out
    return out


def build_mapping(mapping_excel_path: Path) -> dict:
    """Build a mapping dict keyed by (file_key, normalized_column) -> target."""
    wb = pd.ExcelFile(mapping_excel_path)
    if "Sheet1" in wb.sheet_names:
        df = wb.parse("Sheet1")
    else:
        df = wb.parse(0)

    # Columns we expect:
    # - 컬럼 명 (포맷/인코딩)
    # - 파일 명
    # - 표준 컬럼명 (Target)

    mapping = {}

    for _, row in df.iterrows():
        tgt = row.get("표준 컬럼명 (Target)")
        if pd.isna(tgt) or str(tgt).strip() == "":
            continue
        src = row.get("컬럼 명 (포맷/인코딩)")
        if pd.isna(src) or str(src).strip() == "":
            continue
        file_list = row.get("파일 명")
        if pd.isna(file_list):
            file_list = ""

        # Normalize file list into keys
        file_keys = []
        for chunk in re.split(r"[\n,]+", str(file_list)):
            chunk = chunk.strip()
            if not chunk:
                continue
            # Use base name without path
            file_keys.append(Path(chunk).name)

        # If no file specified -> treat as global mapping
        if not file_keys:
            file_keys = ["__global__"]

        src_norm = normalize_col(src)
        for fk in file_keys:
            mapping.setdefault(fk, {})[src_norm] = str(tgt).strip()

    return mapping


def apply_mappings_to_file(src_path: Path, mapping: dict, out_path: Path):
    df = pd.read_excel(src_path, engine="openpyxl")

    file_key = src_path.name
    file_map = mapping.get(file_key, {})
    file_map_global = mapping.get("__global__", {})

    rename_map = {}
    for col in df.columns:
        norm = normalize_col(col)
        if norm in file_map:
            rename_map[col] = file_map[norm]
        elif norm in file_map_global:
            rename_map[col] = file_map_global[norm]

    if rename_map:
        df = df.rename(columns=rename_map)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    df.to_excel(out_path, index=False, engine="openpyxl")
    return rename_map


def main():
    parser = argparse.ArgumentParser(description="Apply column name mappings to normalized Excel files")
    parser.add_argument("--normalized", required=True, help="Folder with normalized Excel files")
    parser.add_argument("--mapping", required=True, help="Mapping Excel file (임상테이블 정리) to read")
    parser.add_argument("--out", required=True, help="Output folder for mapped Excel files")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be renamed without writing files")
    args = parser.parse_args()

    mapping = build_mapping(Path(args.mapping))

    for root, _, files in os.walk(args.normalized):
        for f in files:
            if not f.lower().endswith(".xlsx"):
                continue
            src_path = Path(root) / f
            rel = src_path.relative_to(args.normalized)
            out_path = Path(args.out) / rel

            rename_map = apply_mappings_to_file(src_path, mapping, out_path) if not args.dry_run else {}
            if args.dry_run:
                print(f"[DRY] {rel} -> {out_path} (would rename {len(rename_map)} columns)")
            else:
                print(f"[WRITE] {rel} -> {out_path} (renamed {len(rename_map)} columns)")
                if rename_map:
                    for src, tgt in rename_map.items():
                        print(f"   {src} -> {tgt}")


if __name__ == "__main__":
    main()
