#!/bin/bash
# SERS Analysis - Docker Quick Start Guide

echo "=== SERS Analysis Docker Setup ==="
echo ""
echo "Prerequisites:"
echo "  - Docker installed and running"
echo "  - Data files in ./data directory"
echo ""
echo "Quick commands:"
echo ""
echo "1. Build the image:"
echo "   docker build -t sers-analysis:latest -f infra/Dockerfile ."
echo ""
echo "2. Run with docker-compose (recommended):"
echo "   docker compose -f infra/docker-compose.yml up --build"
echo ""
echo "3. Run with docker run:"
echo "   docker run --rm \\"
echo "     -v \$(pwd)/data:/data:ro \\"
echo "     -v \$(pwd)/results:/results \\"
echo "     -v \$(pwd)/models:/models \\"
echo "     -v \$(pwd)/config/config.yaml:/app/config/config.yaml:ro \\"
echo "     sers-analysis:latest"
echo ""
echo "4. Run in interactive mode for debugging:"
echo "   docker run -it --rm \\"
echo "     -v \$(pwd)/data:/data:ro \\"
echo "     -v \$(pwd)/results:/results \\"
echo "     sers-analysis:latest /bin/bash"
echo ""
echo "5. View container logs:"
echo "   docker compose -f infra/docker-compose.yml logs -f sers-pipeline"
echo ""
echo "6. Stop and clean up:"
echo "   docker compose -f infra/docker-compose.yml down"
echo "   docker system prune"
