from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd


REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_DIR = REPO_ROOT / "notebooks/aecd_clinical_misclassification_outputs"
SUMMARY_PATH = OUTPUT_DIR / "summary.json"


def safe_records(frame: pd.DataFrame) -> list[dict[str, object]]:
    records = frame.to_dict("records")
    for record in records:
        for field, value in record.items():
            if pd.isna(value):
                record[field] = None
    return records


def build_artifact() -> dict[str, object]:
    summary = json.loads(SUMMARY_PATH.read_text(encoding="utf-8"))
    outcome = pd.read_csv(OUTPUT_DIR / "patient_error_review.csv")
    outcome_counts = (
        outcome.groupby("outcome", sort=False)
        .size()
        .rename("count")
        .reset_index()
    )
    cancer = outcome.loc[outcome["cohort_group"].eq("prostate")]
    cancer_noise = (
        cancer.groupby("outcome", sort=False)
        .agg(
            n=("analysis_row", "size"),
            median_noise_sigma_mean=("noise_sigma_mean", "median"),
            median_noise_sigma_p95=("noise_sigma_p95", "median"),
        )
        .reset_index()
    )
    cohort_rates = pd.read_csv(OUTPUT_DIR / "clinical_category_error_rates.csv")
    cohort_rates = cohort_rates.loc[cohort_rates["feature"].eq("cohort_group")].copy()
    cohort_rates["category"] = cohort_rates["category"].replace(
        {
            "prostate disease control": "Disease control",
            "control": "Control",
            "prostate": "Prostate",
        }
    )
    grade_rates = pd.read_csv(OUTPUT_DIR / "clinical_category_error_rates.csv")
    grade_rates = grade_rates.loc[grade_rates["feature"].eq("grade_group")].copy()
    month_rates = pd.read_csv(OUTPUT_DIR / "clinical_category_error_rates.csv")
    month_rates = month_rates.loc[month_rates["feature"].eq("collection_month")].copy()
    hard_cases = pd.read_csv(OUTPUT_DIR / "hard_case_review.csv")
    hard_cases = hard_cases.sort_values(
        ["margin_to_threshold", "analysis_row"]
    ).head(40)
    hard_cases = hard_cases[
        [
            "analysis_row",
            "review_reason",
            "cohort_group",
            "prediction_probability",
            "outcome",
            "margin_to_threshold",
            "noise_sigma_mean",
        ]
    ]
    numeric_tests = pd.read_csv(OUTPUT_DIR / "clinical_numeric_error_tests.csv")

    n_subjects = summary["data"]["subjects"]
    total_repeats = summary["data"]["total_repeats"]
    qc_rate = summary["data"]["qc_pass_rate"]
    fn_rate = summary["hard_case_counts"]["cancer_false_negative_rate"]
    fp_rate = summary["hard_case_counts"]["non_cancer_false_positive_rate"]
    near_threshold = summary["hard_case_counts"]["near_threshold_within_0_05"]
    fn_noise = summary["observed_descriptive_findings"]["cancer_fn_noise_sigma_mean_median"]
    tp_noise = summary["observed_descriptive_findings"]["cancer_tp_noise_sigma_mean_median"]
    fp_disease_control = summary["observed_descriptive_findings"]["false_positive_prostate_disease_control"]

    source = {
        "id": "diagnostic_outputs",
        "label": "Clinical misclassification diagnostic outputs",
        "path": "notebooks/aecd_clinical_misclassification_outputs/summary.json",
        "query": {
            "engine": "duckdb",
            "language": "sql",
            "description": "Reviewed subject-level diagnostic rows generated by the reproducible Python join.",
            "sql": "SELECT * FROM read_csv_auto('notebooks/aecd_clinical_misclassification_outputs/patient_error_review.csv')",
            "tables_used": [
                "notebooks/aecd_api_model_baseline_outputs/clinical_df.xlsx",
                "notebooks/aecd_api_model_mean_spectrum_outputs/oof_predictions.csv",
                "notebooks/aecd_api_model_all_qc_spectra_outputs/subject_qc_noise_summary.csv",
            ],
            "filters": [
                "positive class = prostate",
                "negative classes = control and prostate disease control",
                "OOF decision threshold = 0.40",
                "original subject/sample identifiers omitted from report rows",
            ],
        },
    }
    source_code = {
        "id": "diagnostic_code",
        "label": "Diagnostic analysis code",
        "path": "scripts/analysis/clinical_misclassification_diagnostics.py",
        "query": {
            "engine": "duckdb",
            "language": "sql",
            "description": "Reproducible join, descriptive error comparisons, and figure generation.",
            "sql": "SELECT * FROM read_csv_auto('notebooks/aecd_clinical_misclassification_outputs/clinical_numeric_error_tests.csv')",
            "tables_used": ["scripts/analysis/clinical_misclassification_diagnostics.py"],
        },
    }
    title = "Clinical information review of hard-to-classify SERS patients"
    summary_body = "\n".join(
        [
            "# " + title,
            "",
            "## Technical summary",
            "",
            f"This OOF diagnostic covers **{n_subjects} subjects and {total_repeats:,} repeat spectra**. All subjects have 121 acquisitions, so the clinical generalization unit is 113 subjects rather than 13,673 independent patients.",
            "",
            f"At the 0.40 threshold, the cancer false-negative rate is **{fn_rate:.1%}**, the non-cancer false-positive rate is **{fp_rate:.1%}**, and **{near_threshold} subjects** lie within 0.05 of the threshold.",
            "",
            f"The clearest hard-negative pattern is clinical: **{fp_disease_control} of 21 false positives are prostate disease controls**. Among cancer patients, median repeat noise SD is **{fn_noise:.1f} for false negatives versus {tp_noise:.1f} for true positives**. This is descriptive and exploratory, not causal.",
        ]
    )
    definitions_body = "\n".join(
        [
            "## Scope and definitions",
            "",
            f"The model input is the QC-passed, aligned mean spectrum from the existing clinical run. The report joins the subject-level OOF probability to the local clinical export using the deidentified internal subject key, then removes original identifiers from exposed rows. Overall QC pass rate is **{qc_rate:.1%}**.",
            "",
            "The positive class is `prostate`; `control` and `prostate disease control` are negative. FN and FP comparisons are OOF error diagnostics. Numeric p-values are Mann–Whitney tests without multiplicity correction.",
        ]
    )
    clinical_body = "\n".join(
        [
            "## The dominant clinical ambiguity is prostate disease control",
            "",
            "The false-positive burden is not evenly distributed: prostate disease controls account for most false positives. This is consistent with a clinically difficult negative class, but the analysis does not prove that the model is using PSA or disease severity.",
        ]
    )
    noise_body = "\n".join(
        [
            "## Cancer false negatives have higher repeat-level noise",
            "",
            "Among cancer subjects, the false-negative group has a higher median repeat-noise estimate than the true-positive group. QC pass rate and the number of excluded repeats are similar, so a binary QC gate alone does not capture this difference.",
        ]
    )
    limitations_body = "\n".join(
        [
            "## Limitations and recommended next step",
            "",
            "Parsed PSA and overall stage are entirely missing in the local export; sex and site are constant. Collection-month differences are best treated as an acquisition/batch sensitivity check, not a clinical explanation. The cohort may also contain hospital or batch confounding.",
            "",
            "The next experiment should compare spectrum-only, clinical-only, and fused models on exactly the same subject-level nested folds. Clinical variables must be fitted and transformed inside the training fold, and any improvement should be checked by site, collection period, and repeat-noise strata.",
        ]
    )

    return {
        "surface": "report",
        "manifest": {
            "version": 1,
            "surface": "report",
            "title": title,
            "description": "Technical diagnostic report for subject-level OOF errors and available clinical covariates.",
            "generatedAt": datetime.now(timezone.utc).isoformat(),
            "cards": [
                {
                    "id": "subject_count",
                    "description": "Independent clinical subjects in the OOF diagnostic.",
                    "dataset": "headline",
                    "sourceId": "diagnostic_outputs",
                    "metrics": [{"label": "Subjects", "field": "subjects", "format": "number"}],
                },
                {
                    "id": "repeat_count",
                    "description": "Total repeat spectra represented by the subjects.",
                    "dataset": "headline",
                    "sourceId": "diagnostic_outputs",
                    "metrics": [{"label": "Repeat spectra", "field": "total_repeats", "format": "number"}],
                },
                {
                    "id": "qc_pass_rate",
                    "description": "QC-passed repeat spectra divided by all repeat spectra.",
                    "dataset": "headline",
                    "sourceId": "diagnostic_outputs",
                    "metrics": [{"label": "QC pass rate", "field": "qc_pass_rate", "format": "percent"}],
                },
                {
                    "id": "cancer_fn_rate",
                    "description": "Cancer false negatives divided by all cancer subjects.",
                    "dataset": "headline",
                    "sourceId": "diagnostic_outputs",
                    "metrics": [{"label": "Cancer FN rate", "field": "cancer_fn_rate", "format": "percent"}],
                },
            ],
            "charts": [
                {
                    "id": "outcome_counts",
                    "title": "OOF outcome counts",
                    "subtitle": "113 subject-level OOF predictions at threshold 0.40.",
                    "type": "bar",
                    "dataset": "outcome_counts",
                    "sourceId": "diagnostic_outputs",
                    "encodings": {
                        "x": {"field": "outcome", "type": "nominal", "label": "Outcome"},
                        "y": {"field": "count", "type": "quantitative", "label": "Subjects"},
                        "tooltip": [{"field": "count", "type": "quantitative", "label": "Subjects"}],
                    },
                    "yAxisTitle": "Subjects",
                    "valueFormat": "number",
                    "layout": "full",
                },
                {
                    "id": "cancer_noise",
                    "title": "Repeat noise by cancer prediction outcome",
                    "subtitle": "Median repeat-noise SD among cancer subjects; higher values indicate less repeat-consistent spectra.",
                    "type": "bar",
                    "dataset": "cancer_noise",
                    "sourceId": "diagnostic_outputs",
                    "encodings": {
                        "x": {"field": "outcome", "type": "nominal", "label": "Cancer outcome"},
                        "y": {"field": "median_noise_sigma_mean", "type": "quantitative", "label": "Median noise SD"},
                        "tooltip": [{"field": "n", "type": "quantitative", "label": "Subjects"}],
                    },
                    "yAxisTitle": "Median repeat noise SD",
                    "valueFormat": "number",
                    "layout": "full",
                },
                {
                    "id": "cohort_error_rates",
                    "title": "Misclassification rate by clinical cohort",
                    "subtitle": "Error rate within each cohort; prostate disease controls are the largest false-positive source.",
                    "type": "bar",
                    "dataset": "cohort_error_rates",
                    "sourceId": "diagnostic_outputs",
                    "encodings": {
                        "x": {"field": "category", "type": "nominal", "label": "Clinical cohort"},
                        "y": {"field": "error_rate", "type": "quantitative", "label": "Misclassification rate", "format": "percent"},
                        "tooltip": [
                            {"field": "n", "type": "quantitative", "label": "Subjects"},
                            {"field": "errors", "type": "quantitative", "label": "Errors"},
                        ],
                    },
                    "yAxisTitle": "Misclassification rate",
                    "valueFormat": "percent",
                    "layout": "full",
                },
                {
                    "id": "month_error_rates",
                    "title": "Misclassification rate by collection month",
                    "subtitle": "Acquisition-time sensitivity check; this is not a clinical causal estimate.",
                    "type": "bar",
                    "dataset": "month_error_rates",
                    "sourceId": "diagnostic_outputs",
                    "encodings": {
                        "x": {"field": "category", "type": "ordinal", "label": "Collection month"},
                        "y": {"field": "error_rate", "type": "quantitative", "label": "Misclassification rate", "format": "percent"},
                        "tooltip": [
                            {"field": "n", "type": "quantitative", "label": "Subjects"},
                            {"field": "errors", "type": "quantitative", "label": "Errors"},
                        ],
                    },
                    "yAxisTitle": "Misclassification rate",
                    "valueFormat": "percent",
                    "layout": "full",
                },
            ],
            "tables": [
                {
                    "id": "hard_cases",
                    "title": "Hard-case review rows",
                    "subtitle": "Misclassified or within 0.05 of the decision threshold; original identifiers are omitted.",
                    "dataset": "hard_cases",
                    "sourceId": "diagnostic_outputs",
                    "defaultSort": {"field": "margin_to_threshold", "direction": "asc"},
                    "columns": [
                        {"field": "analysis_row", "label": "Analysis row", "type": "number"},
                        {"field": "review_reason", "label": "Review reason", "type": "text"},
                        {"field": "cohort_group", "label": "Clinical cohort", "type": "text"},
                        {"field": "prediction_probability", "label": "Prediction probability", "format": "number"},
                        {"field": "outcome", "label": "Outcome", "type": "text"},
                        {"field": "margin_to_threshold", "label": "Distance to threshold", "format": "number"},
                        {"field": "noise_sigma_mean", "label": "Mean repeat noise SD", "format": "number"},
                    ],
                },
                {
                    "id": "numeric_tests",
                    "title": "Exploratory numeric comparisons",
                    "subtitle": "Mann–Whitney tests comparing error versus correct groups within cancer and non-cancer strata.",
                    "dataset": "numeric_tests",
                    "sourceId": "diagnostic_outputs",
                    "defaultSort": {"field": "mann_whitney_p", "direction": "asc"},
                    "columns": [
                        {"field": "scope", "label": "Scope", "type": "text"},
                        {"field": "feature_label", "label": "Feature", "type": "text"},
                        {"field": "error_group", "label": "Error group", "type": "text"},
                        {"field": "correct_group", "label": "Correct group", "type": "text"},
                        {"field": "n_error", "label": "Error n", "format": "number"},
                        {"field": "n_correct", "label": "Correct n", "format": "number"},
                        {"field": "mann_whitney_p", "label": "P-value", "format": "number"},
                    ],
                },
            ],
            "sources": [source, source_code],
            "blocks": [
                {"id": "title", "type": "markdown", "body": "# " + title},
                {"id": "summary", "type": "markdown", "sourceId": "diagnostic_outputs", "body": summary_body},
                {"id": "metrics", "type": "metric-strip", "cardIds": ["subject_count", "repeat_count", "qc_pass_rate", "cancer_fn_rate"]},
                {"id": "definitions", "type": "markdown", "sourceId": "diagnostic_outputs", "body": definitions_body},
                {"id": "outcomes_note", "type": "markdown", "sourceId": "diagnostic_outputs", "body": "## OOF errors are concentrated in both cancer FN and hard-negative FP outcomes\n\nThe outcome chart shows that the current threshold produces both false negatives and false positives at the subject level. The exact counts are shown below."},
                {"id": "outcomes_chart", "type": "chart", "chartId": "outcome_counts", "layout": "full"},
                {"id": "clinical_note", "type": "markdown", "sourceId": "diagnostic_outputs", "body": clinical_body},
                {"id": "cohort_chart", "type": "chart", "chartId": "cohort_error_rates", "layout": "full"},
                {"id": "noise_note", "type": "markdown", "sourceId": "diagnostic_outputs", "body": noise_body},
                {"id": "noise_chart", "type": "chart", "chartId": "cancer_noise", "layout": "full"},
                {"id": "month_note", "type": "markdown", "sourceId": "diagnostic_outputs", "body": "## Collection month is a sensitivity signal, not a clinical explanation\n\nError rates rise across the available collection months, but this can reflect batch, operator, or cohort composition. It should be checked with leave-one-month-out or time-blocked validation before adding clinical interpretation."},
                {"id": "month_chart", "type": "chart", "chartId": "month_error_rates", "layout": "full"},
                {"id": "hard_cases_note", "type": "markdown", "sourceId": "diagnostic_outputs", "body": "## The hard-case CSV identifies patients for clinical review\n\nRows are included when the prediction is wrong or lies within 0.05 of the threshold. The exported CSV intentionally uses an internal analysis row and excludes original subject/sample identifiers."},
                {"id": "limitations", "type": "markdown", "sourceId": "diagnostic_outputs", "body": limitations_body},
            ],
        },
        "snapshot": {
            "version": 1,
            "generatedAt": datetime.now(timezone.utc).isoformat(),
            "status": "ready",
            "datasets": {
                "headline": [
                    {
                        "subjects": n_subjects,
                        "total_repeats": total_repeats,
                        "qc_pass_rate": qc_rate,
                        "cancer_fn_rate": fn_rate,
                    }
                ],
                "outcome_counts": safe_records(outcome_counts),
                "cancer_noise": safe_records(cancer_noise),
                "cohort_error_rates": safe_records(cohort_rates),
                "grade_error_rates": safe_records(grade_rates),
                "month_error_rates": safe_records(month_rates),
                "hard_cases": safe_records(hard_cases),
                "numeric_tests": safe_records(numeric_tests),
            },
            "accessIssues": [],
        },
        "sources": [source, source_code],
        "package_info": {
            "root": "aecd_clinical_misclassification_outputs",
            "manifestPath": "artifact.json",
            "snapshotPath": "artifact.json",
        },
    }


if __name__ == "__main__":
    artifact = build_artifact()
    (OUTPUT_DIR / "artifact.json").write_text(
        json.dumps(artifact, ensure_ascii=False, indent=2, allow_nan=False),
        encoding="utf-8",
    )
    print(OUTPUT_DIR / "artifact.json")
