-- =====================================================================
-- 01_measurement_plan.sql — 측정 계획표(엑셀)와 실제 측정 진행을 잇는 ops 스키마
-- WHY: 측정 계획("검체 측정 Lot_Powder_…xlsx", DAY 시트)은 엑셀에만 있고 실제 측정은
--      measurement 스키마에만 있어 진행률을 볼 수 없었다(2026-09-29 사용자 요청: Teams에
--      Power BI로 진행 현황 게시). measurement는 읽기 전용이라 사용자 결정으로 ops 스키마에 둔다.
--        ops.plan_versions        적재한 계획표 파일(버전)
--        ops.measurement_plan     계획표의 검체 한 칸 = 한 행 (DAY·Lot·Paper·군)
--        ops.clinical_exclusions  계획표의 제외사유 목록 시트 (환자 단위 사유 — 대시보드에 내보내지 않음)
--        ops.v_plan_progress      현재 계획 × 실제 측정(환원제 lot BCCP0922) × QC — 사유 텍스트 없음
-- 실행: psql -d aecd_platform -f scripts/db/ops/01_measurement_plan.sql (재실행 안전)
-- 채우기: python scripts/db/ops/load_measurement_plan.py --file <xlsx>
-- 롤백: DROP SCHEMA ops CASCADE;
-- =====================================================================

BEGIN;

DO $$
BEGIN
    IF current_database() <> 'aecd_platform' THEN
        RAISE EXCEPTION 'Wrong database: %. Connect to aecd_platform.', current_database();
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS ops;

CREATE TABLE IF NOT EXISTS ops.plan_versions (
    plan_version_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file     TEXT        NOT NULL,
    file_md5        TEXT        NOT NULL UNIQUE,
    is_current      BOOLEAN     NOT NULL DEFAULT false,
    loaded_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- 현재 계획은 한 벌만
CREATE UNIQUE INDEX IF NOT EXISTS plan_versions_one_current ON ops.plan_versions (is_current) WHERE is_current;

CREATE TABLE IF NOT EXISTS ops.measurement_plan (
    plan_version_id BIGINT NOT NULL REFERENCES ops.plan_versions(plan_version_id) ON DELETE CASCADE,
    sample_id       BIGINT NOT NULL REFERENCES master.samples(sample_id),
    solum_label     TEXT   NOT NULL,
    plan_day        TEXT   NOT NULL,   -- 시트 이름, 예: 'DAY 1' (달력 날짜 아님)
    plan_lot        TEXT   NOT NULL,   -- 예: 'Lot.1'
    paper_no        TEXT   NOT NULL,   -- 예: '#1'
    plan_group      TEXT   NOT NULL,   -- 계획표 열 이름, 예: 'CPAN'
    sheet_cell      TEXT   NOT NULL,   -- 예: 'K3'
    PRIMARY KEY (plan_version_id, sample_id)
);

CREATE TABLE IF NOT EXISTS ops.clinical_exclusions (
    plan_version_id BIGINT  NOT NULL REFERENCES ops.plan_versions(plan_version_id) ON DELETE CASCADE,
    sample_id       BIGINT  NOT NULL REFERENCES master.samples(sample_id),
    solum_label     TEXT    NOT NULL,
    urinary_infection BOOLEAN NOT NULL,   -- 요로감염
    other_cancer    BOOLEAN NOT NULL,     -- 타암이력
    post_treatment  BOOLEAN NOT NULL,     -- 치료후채취
    multi_cancer    BOOLEAN NOT NULL,     -- 다중암
    drop_flag       BOOLEAN NOT NULL,     -- Drop
    yellow_mark     BOOLEAN NOT NULL,     -- 노란표시 (원본 표시 그대로)
    reason          TEXT,                 -- 제외근거 (환자 단위 임상 정보)
    criteria        TEXT    NOT NULL,     -- 예: 'v8'
    PRIMARY KEY (plan_version_id, sample_id)
);

-- 대시보드용: 검체 한 행. 완료 = 환원제 lot BCCP0922로 측정된 기록이 있음(변경 전 측정은 완료로 세지 않음).
-- QC는 experiment.sample_qc에 계산된 검체만(없으면 NULL = 미계산). 제외 사유 텍스트는 넣지 않는다.
CREATE OR REPLACE VIEW ops.v_plan_progress AS
WITH cur AS (SELECT plan_version_id FROM ops.plan_versions WHERE is_current),
meas AS (
    SELECT m.sample_id, min(r.measurement_date) AS first_measured, max(r.measurement_date) AS last_measured,
           count(DISTINCT r.measurement_run_id) AS n_runs, count(*) AS n_points
    FROM measurement.measurements m
    JOIN measurement.runs r ON r.measurement_run_id = m.measurement_run_id
    JOIN measurement.reagent_lots rl ON rl.reagent_lot_id = r.reagent_lot_id
    WHERE m.measurement_role = 'clinical' AND m.status <> 'invalid' AND rl.lot_number = 'BCCP0922'
    GROUP BY m.sample_id
),
qc AS (
    SELECT DISTINCT ON (sample_id) sample_id, dropped_2b, n_fail, n_points
    FROM experiment.sample_qc ORDER BY sample_id, computed_at DESC
)
SELECT p.solum_label, p.plan_day, p.plan_lot, p.paper_no, p.plan_group,
       site.site_code,
       d.cohort_group,
       (e.sample_id IS NOT NULL)                 AS excluded,
       (meas.sample_id IS NOT NULL)              AS measured,
       meas.first_measured, meas.last_measured, meas.n_runs,
       CASE WHEN meas.sample_id IS NULL THEN '미측정'
            WHEN qc.sample_id IS NULL THEN 'QC 미계산'
            WHEN qc.dropped_2b THEN 'QC 탈락'
            ELSE 'QC 통과' END                   AS qc_status,
       round(qc.n_fail::numeric / NULLIF(qc.n_points, 0), 3) AS point_fail_rate
FROM ops.measurement_plan p
JOIN cur USING (plan_version_id)
JOIN master.samples s ON s.sample_id = p.sample_id
JOIN master.subjects subj ON subj.subject_id = s.subject_id
JOIN master.sites site ON site.site_id = subj.site_id
-- 다중암 환자는 진단이 2건이라 검체 자신의 진단만(diagnosis_id = sample_id, 2026-09-29 전 검체 확인)
LEFT JOIN clinical.diagnoses d ON d.subject_id = subj.subject_id AND d.diagnosis_id = s.sample_id
LEFT JOIN ops.clinical_exclusions e ON e.plan_version_id = p.plan_version_id AND e.sample_id = p.sample_id
LEFT JOIN meas ON meas.sample_id = p.sample_id
LEFT JOIN qc ON qc.sample_id = p.sample_id;

COMMIT;
